spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  datasource:
    url: jdbc:postgresql://host.docker.internal:5433/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
