version: '3'

services:

  postgres-test:
    image: 'postgres:14'
    container_name: 'postgres-test'
    volumes:
      - ./postgres:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5433:5432

  data-access-service:
    image: data-access-service
    container_name: data-access-service
    build: ./data-access-service
    volumes:
      - ../src:/opt/app
    ports:
      - 8081:8081