version: '3'

services:

  postgres-test:
    image: 'postgres:14'
    container_name: 'postgres-test'
    volumes:
      - ./postgres:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5433:5432

  registration-service:
    image: registration-service
    container_name: registration-service
    build: ./registration-service
    volumes:
      - ../src:/opt/app
    ports:
      - 8081:8081
    environment:
      - SPRING_PROFILES_ACTIVE=stage