version: '3'

services:

  postgres-test:
    image: 'postgres:14'
    container_name: 'postgres-test'
    volumes:
      - ./postgres:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5434:5432

  eureka-service:
    image: eureka-server
    container_name: eureka-server
    build: ./eureka-server
    volumes:
      - ../src:/opt/app
    ports:
      - 8761:8761

  authentication-service:
    image: authentication-service
    container_name: authentication-service
    build: ./authentication-service
    volumes:
      - ../src:/opt/app
    environment:
      - SPRING_PROFILES_ACTIVE=stage
    ports:
      - 8082:8082

  apigateway-service:
    image: apigateway-service
    container_name: apigateway-service
    build: ./api-gateway
    volumes:
      - ../src:/opt/app
    ports:
      - 8089:8089
    environment:
      - SPRING_PROFILES_ACTIVE=stage

  customer-service:
    image: customer-service
    container_name: customer-service
    build: ./customer-service
    volumes:
      - ../src:/opt/app
    ports:
      - 8081:8081
    environment:
      - SPRING_PROFILES_ACTIVE=stage