request:
  fns:
    api-request: https://api-fns.ru/api/egr
    api-key: bd165f03affe92c87de099fbe9ee28de67f6ca61

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

server:
  port: 8087

spring:
  application:
    name: company-moderation-service
  main:
    web-application-type: none
  kafka:
    bootstrapAddress: localhost:29092
    consumer:
      groupId: consumerModerationGroup
      topicName: companyForReview
    producer:
      topicName: resultModeration


