spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

  kafka:
    server:
      bootstrapAddress: localhost:29092
    cunsumer:
      groupId: consumerGroup
      topicName: resultModeration
    producer:
      topicName: companyForReview


  application:
    name: customer-service

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true



