spring:
  application:
    name: ad-client-registration-landings

  thymeleaf:
    prefix: classpath:/web/

  mvc:
    view:
      prefix: /web/
      suffix: .html
  web:
    resources:
      add-mappings: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
server:
  port: 8080